# Generated by Django 4.0.1 on 2022-02-17 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('hint', models.TextField(blank=True, verbose_name='Hinweis')),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruppe', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1)),
                ('zeile', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(default='')),
                ('start_Jg', models.PositiveSmallIntegerField(default=5, verbose_name='Start in Jahrgang')),
                ('start_SW', models.PositiveSmallIntegerField(default=1, verbose_name='Start in Schulwoche')),
                ('eof', models.PositiveSmallIntegerField(default=25, verbose_name='Eingaben ohne Fehler')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
        migrations.CreateModel(
            name='Schueler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachname', models.CharField(max_length=20)),
                ('vorname', models.CharField(max_length=20)),
                ('klasse', models.CharField(max_length=10)),
                ('jahrgang', models.PositiveSmallIntegerField(default=0)),
                ('kurs', models.CharField(choices=[('Y', 'Gymnasium'), ('R', 'Realschule'), ('H', 'Hauptschule'), ('E', 'E-Kurs'), ('G', 'G-Kurs'), ('A', 'E-Kurs'), ('B', 'E-Kurs'), ('C', 'E-Kurs'), ('i', 'Förderschüler')], default='E', max_length=1)),
                ('kurs_i', models.BooleanField(default=False, editable=False, verbose_name='Förderkind')),
                ('kurs_E', models.BooleanField(default=True, editable=False, verbose_name='E-Kurs')),
                ('datum_start', models.DateField(auto_now_add=True, verbose_name='Startdatum')),
                ('stufe', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('halbjahr', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('voreinst', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Schüler',
                'verbose_name_plural': 'Schüler',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wert')),
                ('text', models.TextField(verbose_name='Text')),
                ('result_unit', models.CharField(blank=True, max_length=20, verbose_name='Einheit Ergebnis')),
                ('tries', models.PositiveSmallIntegerField(default=0, verbose_name='Versuche')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Start')),
                ('end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ende')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.category', verbose_name='Kategorie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.category', verbose_name='Kategorie')),
            ],
        ),
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typA', models.PositiveSmallIntegerField(default=0)),
                ('typB', models.PositiveSmallIntegerField(default=0)),
                ('text', models.CharField(blank=True, max_length=40)),
                ('aufgabe', models.CharField(blank=True, max_length=20)),
                ('protokolltext', models.CharField(blank=True, max_length=20)),
                ('anmerkung', models.CharField(blank=True, max_length=20)),
                ('grafik', models.IntegerField(default=0)),
                ('hilfe1', models.CharField(blank=True, max_length=25)),
                ('hilfe2', models.CharField(blank=True, max_length=25)),
                ('ergebnis', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('loesung', models.CharField(blank=True, max_length=100)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragen', to='core.kategorie')),
            ],
            options={
                'verbose_name': 'Frage',
                'verbose_name_plural': 'Fragen',
            },
        ),
        migrations.CreateModel(
            name='Daten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(blank=True, max_length=5)),
                ('halbjahr', models.PositiveSmallIntegerField(default=0)),
                ('text', models.CharField(blank=True, max_length=30, verbose_name='Aufgabentext')),
                ('aufgabe', models.CharField(blank=True, max_length=20, verbose_name='Aufgaben')),
                ('eingabe', models.CharField(blank=True, max_length=20, verbose_name='Eingabe')),
                ('loesung', models.CharField(blank=True, max_length=20, verbose_name='Lösung')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Start')),
                ('ende', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ende')),
                ('bearbeitungszeit', models.DateTimeField(blank=True, default=None, null=True)),
                ('richtig', models.PositiveSmallIntegerField(default=0)),
                ('zusatz', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('falsch', models.PositiveSmallIntegerField(default=0)),
                ('zaehler_falsch', models.PositiveSmallIntegerField(default=0)),
                ('abbrechen', models.PositiveSmallIntegerField(default=0)),
                ('hilfe', models.PositiveSmallIntegerField(default=0)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daten', to='core.kategorie', verbose_name='Kategorie')),
                ('schueler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daten', to='core.schueler')),
            ],
            options={
                'verbose_name': 'Daten',
                'verbose_name_plural': 'Daten',
            },
        ),
    ]
