# Generated by Django 4.0.3 on 2022-04-06 14:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruppe', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1)),
                ('zeile', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(default='')),
                ('start_jg', models.PositiveSmallIntegerField(default=5, verbose_name='Start in Jahrgang')),
                ('start_sw', models.PositiveSmallIntegerField(default=1, verbose_name='Start in Schulwoche')),
                ('eof', models.PositiveSmallIntegerField(default=25, verbose_name='Eingaben ohne Fehler')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
        migrations.CreateModel(
            name='Schueler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachname', models.CharField(max_length=20)),
                ('vorname', models.CharField(max_length=20)),
                ('klasse', models.CharField(max_length=10)),
                ('jahrgang', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('kurs', models.CharField(choices=[('Y', 'Gymnasium'), ('R', 'Realschule'), ('H', 'Hauptschule'), ('E', 'E-Kurs'), ('G', 'G-Kurs'), ('A', 'A-Kurs'), ('B', 'B-Kurs'), ('C', 'C-Kurs'), ('i', 'Förderschüler')], default='E', max_length=1)),
                ('datum_start', models.DateField(auto_now_add=True, verbose_name='Startdatum')),
                ('stufe', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('halbjahr', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('voreinst', models.IntegerField(default=1, editable=False)),
            ],
            options={
                'verbose_name': 'Schüler',
                'verbose_name_plural': 'Schüler',
            },
        ),
        migrations.CreateModel(
            name='Zaehler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionen', models.CharField(blank=True, max_length=100, verbose_name='Optionen')),
                ('typ_anf', models.SmallIntegerField(default=0)),
                ('typ_end', models.SmallIntegerField(default=0)),
                ('aufgnr', models.PositiveSmallIntegerField(default=0)),
                ('richtig', models.PositiveSmallIntegerField(default=0)),
                ('Extrapunkte', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('richtig_of', models.PositiveSmallIntegerField(default=0)),
                ('falsch', models.PositiveSmallIntegerField(default=0)),
                ('loesung', models.PositiveSmallIntegerField(default=0)),
                ('abbrechen', models.PositiveSmallIntegerField(default=0)),
                ('hilfe', models.PositiveSmallIntegerField(default=0)),
                ('stufe_next', models.PositiveSmallIntegerField(default=0)),
                ('stufe_zaehl', models.PositiveSmallIntegerField(default=0)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaehler', to='core.kategorie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaehler', to='core.schueler', verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Zähler',
                'verbose_name_plural': 'Zähler',
            },
        ),
        migrations.CreateModel(
            name='Protokoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halbjahr', models.PositiveSmallIntegerField(default=0)),
                ('typ', models.CharField(blank=True, max_length=5)),
                ('aufgnr', models.PositiveSmallIntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('value', models.DecimalField(decimal_places=7, max_digits=20, verbose_name='Wert')),
                ('loesung', models.CharField(blank=True, max_length=20, verbose_name='Lösung')),
                ('eingabe', models.CharField(blank=True, max_length=20, verbose_name='Eingabe')),
                ('falsch_eingabe', models.TextField(blank=True, verbose_name='Falscheingabe')),
                ('tries', models.PositiveSmallIntegerField(default=0, verbose_name='Versuche')),
                ('wertung', models.CharField(blank=True, max_length=10, verbose_name='Wertung')),
                ('hilfe', models.PositiveSmallIntegerField(default=0)),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Start')),
                ('bearbeitungszeit', models.FloatField(default=0)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protokoll', to='core.kategorie', verbose_name='Kategorie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protokoll', to='core.schueler', verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Protokoll',
                'verbose_name_plural': 'Protokoll',
            },
        ),
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typA', models.PositiveSmallIntegerField(default=0)),
                ('typB', models.PositiveSmallIntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('aufgabe', models.CharField(blank=True, max_length=80)),
                ('protokolltext', models.CharField(blank=True, max_length=80)),
                ('loesung', models.CharField(blank=True, max_length=100)),
                ('anmerkung', models.CharField(blank=True, max_length=50)),
                ('hilfe1', models.CharField(blank=True, max_length=50)),
                ('hilfe2', models.CharField(blank=True, max_length=50)),
                ('grafik', models.IntegerField(default=0)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragen', to='core.kategorie')),
            ],
            options={
                'verbose_name': 'Frage',
                'verbose_name_plural': 'Fragen',
            },
        ),
        migrations.CreateModel(
            name='Auswahl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80, verbose_name='Text')),
                ('bis_stufe', models.IntegerField(default=0, verbose_name='bis Stufe:')),
                ('bis_jg', models.IntegerField(default=0, verbose_name='bis Jahrgang:')),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategorie')),
            ],
            options={
                'verbose_name': 'Auswahl',
                'verbose_name_plural': 'Auswahl',
            },
        ),
    ]
