# Generated by Django 4.0.3 on 2022-04-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protokoll',
            name='aufgnr',
        ),
    ]
