# Generated by Django 4.0 on 2022-02-25 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daten',
            old_name='zusatz',
            new_name='zaehler_zusatz',
        ),
        migrations.RemoveField(
            model_name='daten',
            name='falsch',
        ),
        migrations.AddField(
            model_name='daten',
            name='zaehler_richtig',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daten',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daten', to='core.kategorie', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='daten',
            name='richtig',
            field=models.BooleanField(default=False),
        ),
    ]
