# Generated by Django 4.0.3 on 2022-04-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_protokoll_aufgnr'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='aufgnr',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
