# Generated by Django 4.0 on 2022-02-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_daten_kategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daten',
            name='kategorie',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kategorie'),
        ),
    ]
