# Generated by Django 4.0 on 2022-02-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_daten_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daten',
            name='start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Start'),
        ),
    ]
