# Generated by Django 4.0.3 on 2022-04-07 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_protokoll_aufgnr'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='frage',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='protokolle', to='core.frage', verbose_name='Frage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protokolle', to='core.kategorie', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protokolle', to='core.schueler', verbose_name='Benutzer'),
        ),
    ]
