# Generated by Django 4.0.1 on 2022-02-14 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_result_result_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Gruppe',
                'verbose_name_plural': 'Gruppen',
            },
        ),
        migrations.CreateModel(
            name='Kategorien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruppe', models.CharField(blank=True, max_length=1)),
                ('zeile', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=20)),
                ('start_Jg', models.PositiveSmallIntegerField(default=5, verbose_name='Start in Jahrgang')),
                ('start_SW', models.PositiveSmallIntegerField(default=1, verbose_name='Start in Schulwoche')),
                ('eof', models.PositiveSmallIntegerField(default=25, verbose_name='Eingaben ohne Fehler')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
        migrations.CreateModel(
            name='Lehrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anrede', models.CharField(max_length=5)),
                ('nachname', models.CharField(max_length=20)),
                ('vorname', models.CharField(max_length=20)),
                ('sprache', models.CharField(default='de', editable=False, max_length=2)),
            ],
            options={
                'verbose_name': 'Lehrer',
                'verbose_name_plural': 'Lehrer',
            },
        ),
        migrations.CreateModel(
            name='Schulen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('schulform', models.CharField(max_length=20)),
                ('nummer', models.IntegerField(default=0, verbose_name='Schulnummer')),
                ('ort', models.CharField(max_length=30, verbose_name='Schulort')),
                ('plz', models.CharField(max_length=5, verbose_name='PLZ des Schulortes')),
                ('Land', models.CharField(default='Hessen', max_length=20, verbose_name='Bundesland')),
                ('Staat', models.CharField(default='DE', editable=False, max_length=2, verbose_name='Land')),
            ],
            options={
                'verbose_name': 'Schule',
                'verbose_name_plural': 'Schulen',
            },
        ),
        migrations.CreateModel(
            name='Schueler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachname', models.CharField(max_length=20)),
                ('vorname', models.CharField(max_length=20)),
                ('klasse', models.CharField(max_length=10)),
                ('jahrgang', models.PositiveSmallIntegerField(default=0)),
                ('kurs', models.CharField(default='E', max_length=1)),
                ('kurs_i', models.BooleanField(default=False, editable=False, verbose_name='Förderkind')),
                ('kurs_E', models.BooleanField(default=True, editable=False, verbose_name='E-Kurs')),
                ('sprache', models.CharField(default='de', editable=False, max_length=20)),
                ('datum_start', models.DateField(auto_now_add=True, verbose_name='Startdatum')),
                ('stufe', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('halbjahr', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('voreinst', models.IntegerField(default=1)),
                ('zaehler_EoF', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('zaehler_Fehler', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('gruppe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Schüler', to='core.gruppen')),
                ('lehrer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Schüler', to='core.lehrer')),
                ('schule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Schüler', to='core.schulen')),
            ],
            options={
                'verbose_name': 'Schüler',
                'verbose_name_plural': 'Schüler',
            },
        ),
        migrations.AddField(
            model_name='lehrer',
            name='schule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lehrer', to='core.schulen'),
        ),
        migrations.AddField(
            model_name='gruppen',
            name='lehrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gruppe', to='core.lehrer'),
        ),
        migrations.AddField(
            model_name='gruppen',
            name='schule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gruppe', to='core.schulen'),
        ),
        migrations.CreateModel(
            name='Fragen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typA', models.PositiveSmallIntegerField(default=0)),
                ('typB', models.PositiveSmallIntegerField(default=0)),
                ('anz', models.PositiveSmallIntegerField(default=10, verbose_name='Anzahl Aufgaben')),
                ('aufgabe', models.CharField(max_length=20)),
                ('protokolltext', models.CharField(max_length=20)),
                ('anmerkung', models.CharField(max_length=20)),
                ('grafik', models.IntegerField(default=0)),
                ('hilfe1', models.CharField(max_length=25)),
                ('hilfe2', models.CharField(max_length=25)),
                ('ergebnis', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('text', models.CharField(max_length=100)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fragen', to='core.kategorien')),
            ],
            options={
                'verbose_name': 'Frage',
                'verbose_name_plural': 'Fragen',
            },
        ),
        migrations.CreateModel(
            name='Daten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(blank=True, max_length=5)),
                ('halbjahr', models.PositiveSmallIntegerField(default=0)),
                ('text', models.CharField(blank=True, max_length=30, verbose_name='Aufgabentext')),
                ('aufgabe', models.CharField(blank=True, max_length=20, verbose_name='Aufgaben')),
                ('eingabe', models.CharField(blank=True, max_length=20, verbose_name='Eingabe')),
                ('loesung', models.CharField(blank=True, max_length=20, verbose_name='Lösung')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Start')),
                ('ende', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ende')),
                ('bearbeitungszeit', models.DateTimeField(blank=True, default=None, null=True)),
                ('richtig', models.PositiveSmallIntegerField(default=0)),
                ('zusatz', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('falsch', models.PositiveSmallIntegerField(default=0)),
                ('zaehler_falsch', models.PositiveSmallIntegerField(default=0)),
                ('abbrechen', models.PositiveSmallIntegerField(default=0)),
                ('hilfe', models.PositiveSmallIntegerField(default=0)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Daten', to='core.kategorien', verbose_name='Kategorie')),
                ('schueler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Daten', to='core.schueler')),
            ],
            options={
                'verbose_name': 'Daten',
                'verbose_name_plural': 'Daten',
            },
        ),
    ]
