# Generated by Django 4.0 on 2022-02-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_daten_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daten',
            name='bearbeitungszeit',
            field=models.FloatField(default=0),
        ),
    ]
