# Generated by Django 4.0.3 on 2022-04-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_protokoll_frage_alter_protokoll_kategorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='frage',
            field=models.IntegerField(default=0, verbose_name='Frage_id'),
        ),
    ]
