# Generated by Django 4.0.1 on 2022-02-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_daten_protokolltext_alter_daten_aufgabe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daten',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
