# Generated by Django 4.0.1 on 2022-02-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_daten_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frage',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
