# Generated by Django 4.0 on 2022-04-21 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_protokoll_frage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schueler',
            old_name='jahrgang',
            new_name='jg',
        ),
    ]
