# Generated by Django 4.0 on 2022-03-03 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_daten_bearbeitungszeit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protokoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halbjahr', models.PositiveSmallIntegerField(default=0)),
                ('typ', models.CharField(blank=True, max_length=5)),
                ('text', models.TextField(blank=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wert')),
                ('eingabe', models.CharField(blank=True, max_length=20, verbose_name='Eingabe')),
                ('loesung', models.CharField(blank=True, max_length=20, verbose_name='Lösung')),
                ('tries', models.PositiveSmallIntegerField(default=0, verbose_name='Versuche')),
                ('richtig', models.BooleanField(default=False)),
                ('zaehler_richtig', models.PositiveSmallIntegerField(default=0)),
                ('zaehler_zusatz', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('zaehler_falsch', models.PositiveSmallIntegerField(default=0)),
                ('abbrechen', models.PositiveSmallIntegerField(default=0)),
                ('hilfe', models.PositiveSmallIntegerField(default=0)),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Start')),
                ('bearbeitungszeit', models.FloatField(default=0)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daten', to='core.kategorie', verbose_name='Kategorie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daten', to='core.schueler', verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Daten',
                'verbose_name_plural': 'Daten',
            },
        ),
        migrations.DeleteModel(
            name='Daten',
        ),
    ]
