# Generated by Django 4.0 on 2022-04-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_jahrgang_schueler_jg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zaehler',
            old_name='optionen',
            new_name='optionen_text',
        ),
        migrations.AlterField(
            model_name='schueler',
            name='stufe',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
