# Generated by Django 4.0 on 2022-03-03 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_protokoll_delete_daten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protokoll',
            name='abbrechen',
        ),
        migrations.RemoveField(
            model_name='protokoll',
            name='richtig',
        ),
        migrations.RemoveField(
            model_name='protokoll',
            name='zaehler_falsch',
        ),
        migrations.RemoveField(
            model_name='protokoll',
            name='zaehler_richtig',
        ),
        migrations.RemoveField(
            model_name='protokoll',
            name='zaehler_zusatz',
        ),
        migrations.RemoveField(
            model_name='schueler',
            name='kurs_E',
        ),
        migrations.RemoveField(
            model_name='schueler',
            name='kurs_i',
        ),
        migrations.AddField(
            model_name='protokoll',
            name='falsch_eingabe',
            field=models.TextField(blank=True, verbose_name='Falscheingabe'),
        ),
        migrations.AddField(
            model_name='protokoll',
            name='wertung',
            field=models.CharField(blank=True, max_length=5, verbose_name='Wertung'),
        ),
        migrations.AlterField(
            model_name='frage',
            name='ergebnis',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protokoll', to='core.kategorie', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protokoll', to='core.schueler', verbose_name='Benutzer'),
        ),
        migrations.CreateModel(
            name='zaehler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falsch', models.PositiveSmallIntegerField(default=0)),
                ('loesung', models.PositiveSmallIntegerField(default=0)),
                ('abbrechen', models.PositiveSmallIntegerField(default=0)),
                ('hilfe', models.PositiveSmallIntegerField(default=0)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaehler', to='core.kategorie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaehler', to='core.schueler', verbose_name='Benutzer')),
            ],
        ),
    ]
