# Generated by Django 4.0.1 on 2022-02-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_frage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frage',
            name='anmerkung',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='frage',
            name='hilfe1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='frage',
            name='hilfe2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='frage',
            name='protokolltext',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
