# Generated by Django 4.0 on 2022-04-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_optionen_zaehler_optionen_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaehler',
            name='optionen',
            field=models.ManyToManyField(to='core.Auswahl'),
        ),
    ]
