# Generated by Django 4.0 on 2022-03-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_protokoll_abbrechen_remove_protokoll_richtig_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protokoll',
            options={'verbose_name': 'Protokoll', 'verbose_name_plural': 'Protokoll'},
        ),
        migrations.AlterModelOptions(
            name='zaehler',
            options={'verbose_name': 'Zähler', 'verbose_name_plural': 'Zähler'},
        ),
        migrations.RemoveField(
            model_name='frage',
            name='ergebnis',
        ),
    ]
