# Generated by Django 4.0.3 on 2022-05-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_zaehler_optionen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protokoll',
            old_name='frage',
            new_name='frage_id',
        ),
        migrations.AlterField(
            model_name='zaehler',
            name='optionen',
            field=models.ManyToManyField(to='core.auswahl'),
        ),
    ]
