# Generated by Django 4.0 on 2022-03-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_frage_aufgabe_alter_frage_protokolltext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategorie',
            name='function',
        ),
        migrations.AddField(
            model_name='frage',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
