# Generated by Django 4.0 on 2022-03-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_kategorie_function_frage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='value',
            field=models.DecimalField(decimal_places=7, max_digits=20, verbose_name='Wert'),
        ),
    ]
