# Generated by Django 4.0 on 2022-03-04 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_protokoll_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frage',
            name='slug',
        ),
    ]
