# Generated by Django 4.0 on 2022-03-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_frage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='aufgnr',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Aufgabe Nr.'),
        ),
        migrations.AddField(
            model_name='zaehler',
            name='stufe_next',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zaehler',
            name='stufe_zaehl',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
