# Generated by Django 4.0 on 2022-06-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_frage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='typ',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
