# Generated by Django 4.0 on 2022-03-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_protokoll_aufgnr_zaehler_stufe_next_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaehler',
            name='aufgnr',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
