# Generated by Django 4.0.3 on 2022-03-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_zaehler_aufgnr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protokoll',
            name='aufgnr',
        ),
        migrations.AddField(
            model_name='zaehler',
            name='Extrapunkte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='zaehler',
            name='richtig',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
