# Generated by Django 4.0 on 2022-06-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_protokoll_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaehler',
            name='optionen_text',
            field=models.CharField(default='', max_length=40, verbose_name='Optionen'),
        ),
    ]
