# Generated by Django 4.0 on 2022-03-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_protokoll_aufgnr_zaehler_extrapunkte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaehler',
            name='richtig_of',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
