# Generated by Django 4.0 on 2022-06-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_zaehler_optionen_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaehler',
            name='optionen_text',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Optionen'),
        ),
    ]
