# Generated by Django 4.0 on 2022-03-10 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_zaehler_richtig_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auswahl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auswahl_text', models.CharField(max_length=80)),
                ('ab_stufe', models.IntegerField(default=0)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategorie')),
            ],
        ),
    ]
