# Generated by Django 4.0 on 2022-06-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_zaehler_optionen_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategorie',
            name='gruppe',
        ),
    ]
