# Generated by Django 4.0 on 2022-06-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_kategorie_gruppe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protokoll',
            name='falsch_eingabe',
        ),
        migrations.RemoveField(
            model_name='protokoll',
            name='frage_id',
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='hilfe',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hilfe'),
        ),
    ]
