# Generated by Django 4.0 on 2022-03-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_auswahl_options_remove_auswahl_auswahl_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auswahl',
            name='bis_jg',
            field=models.IntegerField(default=0, verbose_name='bis Jahrgang:'),
        ),
    ]
