# Generated by Django 4.0 on 2022-03-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auswahl_bis_jg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategorie',
            old_name='start_Jg',
            new_name='start_jg',
        ),
        migrations.RenameField(
            model_name='kategorie',
            old_name='start_SW',
            new_name='start_sw',
        ),
    ]
