# Generated by Django 4.0 on 2022-06-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_protokoll_hilfe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaehler',
            name='hinweis',
            field=models.CharField(blank=True, max_length=40, verbose_name='Lösung/Hilfe'),
        ),
    ]
