# Generated by Django 4.0 on 2022-06-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_protokoll_grafik'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='pro_text',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='grafik',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
