# Generated by Django 4.0 on 2022-06-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_protokoll_pro_text_alter_protokoll_grafik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='grafik',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
