# Generated by Django 4.0.3 on 2022-03-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_protokoll_wertung'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaehler',
            name='optionen',
            field=models.CharField(blank=True, max_length=100, verbose_name='Optionen'),
        ),
    ]
