# Generated by Django 4.0.3 on 2022-04-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_zaehler_optionen'),
    ]

    operations = [
        migrations.AddField(
            model_name='schueler',
            name='rating_gesamt',
            field=models.BooleanField(default=True, verbose_name='Rating Gesamt'),
        ),
        migrations.AddField(
            model_name='schueler',
            name='rating_kurs',
            field=models.BooleanField(default=True, verbose_name='Rating Kurs'),
        ),
        migrations.AddField(
            model_name='schueler',
            name='rating_schule',
            field=models.BooleanField(default=True, verbose_name='Rating Schule'),
        ),
        migrations.AddField(
            model_name='zaehler',
            name='typ_anf',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zaehler',
            name='typ_end',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
