# Generated by Django 4.0.3 on 2022-04-04 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_schueler_rating_gesamt_schueler_rating_kurs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protokoll',
            name='typ',
        ),
        migrations.AddField(
            model_name='protokoll',
            name='frage',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='protokoll', to='core.frage', verbose_name='Frage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schueler',
            name='letzte',
            field=models.DateTimeField(auto_now_add=True, default=0, verbose_name='letzte Anmeldung'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schueler',
            name='start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registrierung'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auswahl',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auswahl', to='core.kategorie'),
        ),
    ]
