# Generated by Django 4.0 on 2022-07-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_protokoll_grafik'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='anmerkung',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='pro_text',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
