# Generated by Django 4.0.3 on 2022-04-04 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_protokoll_typ_protokoll_frage_schueler_letzte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protokoll',
            name='frage',
        ),
        migrations.RemoveField(
            model_name='schueler',
            name='letzte',
        ),
        migrations.RemoveField(
            model_name='schueler',
            name='rating_gesamt',
        ),
        migrations.RemoveField(
            model_name='schueler',
            name='rating_kurs',
        ),
        migrations.RemoveField(
            model_name='schueler',
            name='rating_schule',
        ),
        migrations.RemoveField(
            model_name='schueler',
            name='start',
        ),
        migrations.RemoveField(
            model_name='zaehler',
            name='typ_anf',
        ),
        migrations.RemoveField(
            model_name='zaehler',
            name='typ_end',
        ),
        migrations.AddField(
            model_name='protokoll',
            name='typ',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='auswahl',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategorie'),
        ),
    ]
