# Generated by Django 4.0 on 2022-07-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_protokoll_anmerkung_alter_protokoll_pro_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='grafik',
            field=models.JSONField(),
        ),
    ]
