# Generated by Django 4.0 on 2022-07-05 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_protokoll_grafik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='eingabe',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protokolle', to='core.kategorie'),
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='loesung',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='wertung',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
