# Generated by Django 4.0.3 on 2022-04-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_protokoll_frage_remove_schueler_letzte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protokoll',
            name='typ',
        ),
        migrations.AddField(
            model_name='zaehler',
            name='typ_anf',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zaehler',
            name='typ_end',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protokoll', to='core.frage', verbose_name='Frage'),
        ),
    ]
