# Generated by Django 4.0.3 on 2022-04-04 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_protokoll_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='frage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='protokoll', to='core.frage', verbose_name='Frage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protokoll', to='core.schueler', verbose_name='Benutzer'),
        ),
    ]
