# Generated by Django 4.0.3 on 2022-04-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_protokoll_frage_alter_protokoll_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protokoll',
            name='frage',
        ),
    ]
