# Generated by Django 4.0 on 2022-07-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_schueler_e_kurs_alter_schueler_halbjahr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='halbjahr',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
