# Generated by Django 4.0 on 2022-07-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_protokoll_halbjahr'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='titel',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='typ',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zaehler',
            name='hinweis',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hilfe/Hinweis'),
        ),
    ]
