# Generated by Django 4.0 on 2022-07-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_protokoll_titel_alter_protokoll_typ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaehler',
            name='hinweis',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
