# Generated by Django 4.0.3 on 2022-04-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_protokoll_frage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protokoll',
            name='frage',
        ),
    ]
