# Generated by Django 4.0 on 2022-07-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_zaehler_hinweis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorie',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
