# Generated by Django 4.0.3 on 2022-04-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_protokoll_frage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorie',
            name='zeile',
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
    ]
