# Generated by Django 4.0 on 2022-03-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='titel',
            new_name='title',
        ),
    ]
